artifacts_root : artifacts

# Cofiguration of data ingestion part
data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/alaminbhuyan/End-To-End-ML-Project-Dataset/raw/main/data.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion